project_id = "lzssqygnetvznmfubwmr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lzssqygnetvznmfubwmr.supabase.co"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[storage]
enabled = true
file_size_limit = "50MiB"

[functions.semantic-search]
verify_jwt = false

[functions.document-processor]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.test-function]
verify_jwt = false

[functions.hybrid-search-chunks]
verify_jwt = false

[functions.process-legal-query]
verify_jwt = false

[functions.query-router]
verify_jwt = false